export const FETCH_PLAYERS_SUCCESS = 'FETCH_PLAYERS_SUCCESS';
export const CREATE_PLAYER_SUCCESS = 'CREATE_PLAYER_SUCCESS';
export const UPDATE_PLAYER_SUCCESS = 'UPDATE_PLAYER_SUCCESS';
export const DELETE_PLAYER_SUCCESS = 'DELETE_PLAYER_SUCCESS';
export const SORTED_PLAYERS_SUCCESS = 'SORTED_PLAYERS_SUCCESS';
export const ADVANCE_PAGE_SUCCESS = 'ADVANCE_PAGE_SUCCESS';
export const FIRST_PAGE_SUCCESS = 'FIRST_PAGE_SUCCESS';
